### ISSUE TITLE
Node doesn't start

### ISSUE THREAD

**Issue by arhuaco** [decentraland/decentraland-node#18]
It gets stuck here:
```
bin/start 
[info] Chain is loading.
[info] Checkpoints are enabled.
[info] Coin cache is enabled.
[info] Content server listening on port 9301
[info] Opening ChainDB...
[info] Chain is loading.
[info] Checkpoints are enabled.
[info] Coin cache is enabled.
```

**Comment by dospunk** [comment]
It would be helpful to include some info on how to recreate this bug. What OS are you using? Are you running natively or in Docker?

**Comment by arhuaco** [comment]
I am using a virtualbox VM with Ubuntu 16.04. Native inside of the VM.

I haven't used this in a while. After a "git pull" it is working.

**Comment by dospunk** [comment]
Don't forget to mark as closed then!
