### ISSUE TITLE
node:6) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit

### ISSUE THREAD

**Issue by jaimeblasco** [decentraland/decentraland-node#19]
The node has been working fine for the last few days. But after a while I get the following error and the node doesn't anymore:

Attaching to bronzeagenode_app_1
app_1  | [info] Chain is loading.
app_1  | [info] Checkpoints are enabled.
app_1  | [info] Coin cache is enabled.
app_1  | [info] Content server listening on port 9301
app_1  | [info] Opening ChainDB...
app_1  | [info] Chain is loading.
app_1  | [info] Checkpoints are enabled.
app_1  | [info] Coin cache is enabled.
app_1  | [info] ChainDB successfully loaded.
app_1  | [info] Chain State: hash=000000f0cb40108fee818058eef4d1bdd5dd10dae00fe159594139dc92f3af20 tx=8298 coin=8276.
app_1  | [info] Chain Height: 8275
app_1  | [debug] Memory: rss=65mb, js-heap=23/39mb native-heap=25mb
app_1  | [info] Chain Height: 8275
app_1  | [debug] Memory: rss=65mb, js-heap=23/39mb native-heap=25mb
app_1  | [warning] P2SH has been activated.
app_1  | [debug] Memory: rss=66mb, js-heap=23/39mb native-heap=26mb
app_1  | [info] Chain is fully synced (height=8275).
app_1  | [debug] Memory: rss=66mb, js-heap=23/39mb native-heap=26mb
app_1  | [info] Mempool loaded (maxsize=97656.25kb).
app_1  | [info] Miner loaded (flags=mined by decentraland-node).
app_1  | [info] Pool loaded (maxpeers=8).
app_1  | [info] HTTP server listening on 0.0.0.0 (port=8301).
app_1  | [info] HTTP server loaded.
app_1  | [info] HTTP API key: REMOVED
app_1  | [info] HTTP Service API key: REMOVED
app_1  | [info] Added 25 hashes to WalletDB filter.
app_1  | [info] Added 3 outpoints to WalletDB filter.
app_1  | [debug] Rolled back to same height (8275).
app_1  | [info] WalletDB is scanning 1 blocks.
app_1  | [info] Scanning from block 000000f0cb40108fee818058eef4d1bdd5dd10dae00fe159594139dc92f3af20.
app_1  | [info] Scanning block 000000f0cb40108fee818058eef4d1bdd5dd10dae00fe159594139dc92f3af20 (8275).
app_1  | [warning] Already saw WalletDB block (8275).
app_1  | [info] Finished scanning 1 blocks.
app_1  | [info] Rebroadcasting 3 WalletDB transactions.
app_1  | [info] WalletDB loaded (depth=2, height=8275, start=0).
app_1  | [error] Verification failure: txn-already-known (code=alreadyknown, score=0, hash=9f7f1ae6abd307cd489d6f38408caf26de2abc7f58ceaf4c1556442ed32e610f)
app_1  | [warning] Verification failed for tx: 9f7f1ae6abd307cd489d6f38408caf26de2abc7f58ceaf4c1556442ed32e610f.
app_1  | [warning] Attempting to broadcast anyway...
app_1  | [error] Verification failure: txn-already-known (code=alreadyknown, score=0, hash=e822d440ab57a14c7a0a4d993c839a1db7a41bb266d36fac548baee3bcbd0a44)
app_1  | [warning] Verification failed for tx: e822d440ab57a14c7a0a4d993c839a1db7a41bb266d36fac548baee3bcbd0a44.
app_1  | [warning] Attempting to broadcast anyway...
app_1  | [error] Verification failure: txn-already-known (code=alreadyknown, score=0, hash=b04f2bb8f24ebe2949201fc643f789d08611d5ba142f01eddddf42fc5fdf48d7)
app_1  | [warning] Verification failed for tx: b04f2bb8f24ebe2949201fc643f789d08611d5ba142f01eddddf42fc5fdf48d7.
app_1  | [warning] Attempting to broadcast anyway...
app_1  | [info] Wallet opened (primary).
app_1  | [info] TXDB loaded for primary.
app_1  | [info] TXDB State: tx=3 coin=3.
app_1  | [info] Balance: unconfirmed=0.0 confirmed=0.0.
app_1  | [info] Loaded wallet with id=primary wid=1 address=REMOVED
app_1  | [info] Pool server listening on 0.0.0.0 (port=2301).
app_1  | [info] Node is loaded.
app_1  | [info] Starting miner ...
app_1  | (node:6) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
app_1  | [debug] Error: socket hang up
app_1  |     at createHangUpError (_http_client.js:253:15)
app_1  |     at Socket.socketCloseListener (_http_client.js:285:23)
app_1  |     at emitOne (events.js:101:20)
app_1  |     at Socket.emit (events.js:188:7)
app_1  |     at TCP._handle.close [as _onclose] (net.js:501:12)
app_1  | [error] socket hang up
bronzeagenode_app_1 exited with code 1

**Comment by maraoz** [comment]
@jaimeblasco thanks for reporting, we'll look into this

**Comment by russelldc** [comment]
Seeing this too.

**Comment by martriay** [comment]
Not needed anymore as we moved to IPFS.
