### ISSUE TITLE
FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by vdg0** [decentraland/decentraland-node#28]
Core i5-3320M CPU @ 2.60GHz
8GB RAM DDR3 1600mhz

Log crash output:
[log_node.txt](https://github.com/decentraland/bronzeage-node/files/967951/log_node.txt)

Is this issue duplicated?
Cheers, vdg

**Comment by Faeranne** [comment]
Having the same error here: [crash.txt](https://github.com/decentraland/bronzeage-node/files/988857/crash.txt)

Core i5-4440 CPU @ 3.10GHz
32GB RAM DDR3 1600mhz
node v6.10.2
Ubuntu 17.04

**Comment by thoragio** [comment]
Try upgrading your node version. The README states "The current decentraland node requires NodeJS v7.4.0 or higher".

**Comment by vdg0** [comment]
My last log was running NodeJS v7.9.0 n_n"

**Comment by martriay** [comment]
Not needed anymore as we moved to IPFS.
