### ISSUE TITLE
Worlds and height

### ISSUE THREAD

**Issue by ghost** [decentraland/decentraland-node#43]
i just found out about this project and really love it, especially since it's similar to an idea i myself had a while ago. but i have two questions:

1) often times virtual worlds like second life, wow, etc have multiple worlds/dimensions. how will decentraland handle this? child blockchains? sister blockchains? not at all? i think to have everything laid out on a single flat world sets a lot of limitations on what can be made.

2) how is height (or even depth) handled in decentraland? can everyone go into the sky as high as they want? can you even go underground? having a z-axis in the world/chain would make a lot of things more complicated. you'd need to purchase the tiles below/above you if you want to make very high projects. and what about rendering, light, etc? but i think not having a z-axis might create even more limitations. allowing everyone to go as high/low on their tile as they want to would create problems. setting a max height would create even more problems and limit users. and without allowing them to purchase space above/below them there's nothing they can do about it.

**Comment by ghost** [comment]
reposted this on the forum since it seems more appropriate there

**Comment by eordano** [comment]
Link: https://forum.decentraland.org/topic/5/worlds-and-height
