### ISSUE TITLE
Resources and downloading

### ISSUE THREAD

**Issue by ghost** [decentraland/decentraland-node#44]
so as of now (and in the planned future) every kind of resource is supplied to the clients via torrent, right? isn't that going to be very inefficient (especially on slow connections) when tiles start to actually get populated? especially with lots of resources like detailed graphics, animations, sounds, scripts, etc. i think some kind of default resource pack that's built into the client, that includes stuff that can be used by tile owners without requiring the user to download anything would be very useful. some basic textures, sounds, etc

does the current system include some kind of caching? or is something planned? what if you visit a tile, go out of it and back again? redownloading everything, even if there was no change to the tile wouldn't make sense. and what if someone who owns multiple tiles next to each other uses the same resources for all of them. do you have to download all of them one by one?

**Comment by ghost** [comment]
reposted this on the forum - can be closed here

**Comment by eordano** [comment]
Link: https://forum.decentraland.org/topic/6/resources-and-downloading
