### ISSUE TITLE
Provide name and icon for the electron app

### ISSUE THREAD

**Issue by stefek99** [decentraland/decentraland-node#47]
<img width="673" alt="screen shot 2017-06-28 at 07 53 29" src="https://user-images.githubusercontent.com/249703/27624046-126a1f16-5bd7-11e7-8654-18aa6b93d1e5.png">

**Comment by KurzGedanke** [comment]
There is no real electron app. This are spawns of `webtorrent-hybrid` which is just used for the torrent delivering the tiles content and has no interface.

**Comment by stefek99** [comment]
https://github.com/webtorrent/webtorrent-hybrid

>  It creates a hidden Electron process (which is based on Chromium, so WebRTC support is great!) and communicates with that process to enable WebRTC in Node.js. This adds a lot of overhead, so we are looking forward to using a pure JavaScript implementation, like perhaps Node-RTCPeerConnection when it's ready.

OK, cool, thanks.
