### ISSUE TITLE
website is not working

### ISSUE THREAD

**Issue by ghost** [decentraland/decentraland-node#73]
When I open site in every section it says "Loading...". When refreshing I can see in terminal 

> Executing RPC call getblockchaininfo with params []
Executing RPC call getnewaddress with params []
Executing RPC call getminerinfo with params []
Getting mined tiles
[ERROR] Error trying to execute the rpc call getblockchaininfoBad auth.
[ERROR] Error trying to execute the rpc call getnewaddressBad auth.
[ERROR] Error trying to execute the rpc call getminerinfoBad auth.
[ERROR] Error trying to get the tiles. Bad auth.

running Ubuntu 17.04

**Comment by ghost** [comment]
rest of the code runs normally

**Comment by eordano** [comment]
Are you using the correct `--apikey`?

**Comment by ghost** [comment]
I an stupid. Was
`export $RPC_API_KEY`
instead of
`export RPC_API_KEY`
